apiVersion: v1
kind: Service
metadata:
  labels:
    app: zprofessors-api-dpl
  name: zprofessors-api-svc
spec:
  ports:
  - port: 3100
    protocol: TCP
    targetPort: 3100
  selector:
    app: zprofessors-api-dpl
