apiVersion: v1
kind: Service
metadata:
  labels:
    app: zstudents-api-dpl
  name: zstudents-api-svc
spec:
  ports:
  - port: 3000
    protocol: TCP
    targetPort: 3000
  selector:
    app: zstudents-api-dpl
