apiVersion: v1
kind: Service
metadata:
  namespace: zschool
  labels:
    app: zstudents-db-dpl
  name: zstudents-db-svc
spec:
  ports:
  - port: 3306
    protocol: TCP
    targetPort: 3306
  selector:
    app: zstudents-db-dpl
