apiVersion: v1
kind: Service
metadata:
  labels:
    app: zstudents-web-dpl
  name: zstudents-web-svc
  namespace: zschool
spec:
  type: NodePort
  ports:
  - port: 4200
    protocol: TCP
    targetPort: 4200
    nodePort: 30010
  selector:
    app: zstudents-web-dpl
